name: 01 - Hello QuickStay 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  greet: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout the Code
        uses: actions/checkout@v4 

      - name: Show environment info
        run: |
          echo "Hello QuickStay!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Commit: ${{ github.sha }}"

      - name: List project files
        run: ls -la 